# Google App Engine Configuration for UNIGRC-M
runtime: nodejs20

# Instance Class F2 is recommended for Node.js apps with moderate memory usage.
# F1 (default) has 256MB RAM / 600MHz CPU
# F2 has 512MB RAM / 1.2GHz CPU
# F4 has 1024MB RAM / 2.4GHz CPU
instance_class: F2

# Automatic scaling is the default and recommended for most web apps.
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

# Environment variables should be set via:
# gcloud app deploy --set-env-vars="DATABASE_URL=...,SESSION_SECRET=..."
# Or by using a .env file (not recommended for git) or Secret Manager.
# We define the keys here for documentation, but values should be injected at deploy time.
env_variables:
  NODE_ENV: 'production'
  # DATABASE_URL: 'Set this during deployment'
  # SESSION_SECRET: 'Set this during deployment'
  # OPENAI_API_KEY: 'Set this during deployment'

# Handlers define how to route requests.
# The default handler serves the app.
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
