# Cloud Build configuration for Frontend
# Deploys to Firebase Hosting
# Triggered on push to main branch

steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci', '--legacy-peer-deps']
    id: 'install-dependencies'

  # Build the frontend with Vite
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export NODE_ENV=production
        echo "🔨 Building frontend..."
        npx vite build
        echo "✅ Frontend built"
        ls -la dist/public/
    id: 'build-frontend'

  # Deploy to Firebase Hosting
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Deploying to Firebase Hosting..."
        npm install -g firebase-tools
        firebase deploy --only hosting --project=$PROJECT_ID
        echo "✅ Deployed to Firebase Hosting"
    id: 'deploy-firebase'

# Build timeout
timeout: '1800s'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
